baseurl = "/"
languageCode = "en-us"
title = "미완성의신"
theme = "hugo-lithium"
googleAnalytics = "UA-145407326-5"
disqusShortname = "hugoblog-4"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Unfinishedgod"
[[menu.main]]
    name = "Facebook"
    url = "https://www.facebook.com/shjj08"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"

    favicon = "Gareth_Frank_Bale_circle_index.ico"

    [params.logo]
    url = "Gareth_Frank_Bale.PNG"
    width = 50
    height = 50
    alt = "Logo"

